#!/bin/sh

if [ -z "$PLANT_LISP" ]; then
    if [ -x `which sbcl` ]; then
        export PLANT_LISP=sbcl
    elif [ -x `which ccl` ]; then
        export PLANT_LISP=ccl
    elif [ -x `which clisp` ]; then
        export PLANT_LISP=clisp
    else
        echo "Unable to automatically find a suitable lisp for plant."
        echo "Please set the PLANT_LISP env var with the path to your lisp executable."
        exit 1
    fi
fi

if [ -z "$PLANT_HOME" ]; then
    plant_path=`readlink -f $0`
    export PLANT_HOME=`dirname $plant_path`
fi

PLANT_BIN=${PLANT_HOME}/bin/plant

if [ ! -x ${PLANT_BIN} ]; then
    echo "Looks like this is the first time you're running plant."
    echo "I'm going to try and build it with either clisp, sbcl, or ccl."
    echo "If you don't have any of these then plant can't run."
    echo
    echo "Press any key to continue, or Ctrl-c to abort."
    read _

    if [ -x `which clisp` ]; then
        echo "Building plant with clisp"
        clisp -q \
            -x "(load \"${PLANT_HOME}/third_party/asdf.lisp\") (load \"${PLANT_HOME}/build_plant.lisp\")"
    elif [ -x `which sbcl` ]; then
        echo "Building plant with sbcl"
        sbcl --noinform \
            --load ${PLANT_HOME}/asdf.lisp \
            --script ${PLANT_HOME}/build_plant.lisp
    fi
    
    if [ ! -x ${PLANT_BIN} ]; then
        echo "Unable to build plant. :("
        echo "Please consider providing any terminal output in a github issue."
        exit 1
    fi
fi

if [ -x `which ${PLANT_LISP}` ]; then
    ${PLANT_BIN} -- $@
else
    echo "I wasn't able to find a supported lisp. Please create a github issue to request support for your preferred environment. :)"
    exit 1
fi
